### PR TITLE
Add fuzzy shortcut Finder, Add shortcut editor and filter shortcuts detected

### PR DESCRIPTION
**Pull request by goanpeca**
Is this the right way to to this @blink1073 ?

### CODE REVIEW

**Comment by goanpeca** [comment]
Hmmm can you rebase @blink1073 ?

**Comment by blink1073** [comment]
I did a rebase, so you'll probably have to as well.

**Comment by goanpeca** [comment]
I did but now It says in github `This pull request contains merge conflicts that must be resolved.` ... bummer

**Comment by goanpeca** [comment]
Ok that was weird process to merge... hmm I think is fine now...

**Comment by blink1073** [comment]
Woot!

**Pull request merged**
